name: arXiv to Discord

on:
  schedule:
    - cron: "50 0 * * 0,1,2,3,4,5,6"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.5"
      - name: image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.3.2"

      - name: Install dependencies
        run: poetry install

      - name: Run script
        run: poetry run python src/main.py
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
